name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  #v6.0.3

      - name: Setup Compact Compiler
        uses: midnightntwrk/setup-compact-action@836895c8fffbbea6bd986af2b17e8941ff29d1f8
        with:
          compact-version: '0.31.0'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e  #v6.4.0
        with:
          node-version: "24"

      - name: Update NPM
        run: |
          npm install -g npm@latest
          npm --version

      - name: Install dependencies
        run: npm ci

      - name: Compile and test contract
        working-directory: contract
        run: |
          npm run ci

      - name: api
        working-directory: api
        run: |
          npm run ci

      - name: Compile pgp-cli
        working-directory: pgp-cli
        run: |
          npm run ci

      - name: Compile pgp-ui
        working-directory: pgp-ui
        run: |
          npm run ci
